import {
  Recycler,
  LotMatch,
  PriceBoardItem,
  CustomerPickupRequest,
  SafetyItem,
  MaterialCategory,
  RecyclerRateCard,
} from '@/types/database';

export const CURRENT_RECYCLER: Recycler = {
  id: 'a0000000-0000-0000-0000-000000000001',
  business_name: 'M/s Fozia Traders (E-Waste Dismantler)',
  facility_location: { lat: 28.7041, lng: 77.3025 },
  registration_number: 'DPCC/E-WASTE/DISM/033',
  registration_authority: 'DPCC (Delhi Pollution Control Committee)',
  authorization_status: 'verified',
  pickup_available: true,
  avg_rating: 4.8,
};

export const MOCK_CATEGORIES: MaterialCategory[] = [
  { parent_code: 'PCB', parent_name: 'Printed Circuit Boards', sub_code: 'mobile_pcb', sub_name: 'Mobile Phone PCB / Motherboard', is_hazardous: true, epr_schedule1_hint: 'ITEW1' },
  { parent_code: 'PCB', parent_name: 'Printed Circuit Boards', sub_code: 'computer_motherboard', sub_name: 'Computer / Laptop Motherboard', is_hazardous: true, epr_schedule1_hint: 'ITEW2' },
  { parent_code: 'BATTERY', parent_name: 'Batteries', sub_code: 'li_ion_mobile_laptop', sub_name: 'Lithium-Ion / Li-Polymer Battery', is_hazardous: true, epr_schedule1_hint: 'Battery Rules' },
  { parent_code: 'BATTERY', parent_name: 'Batteries', sub_code: 'lead_acid_ups_inverter_auto', sub_name: 'Lead Acid (Inverter / UPS / Auto)', is_hazardous: true, epr_schedule1_hint: 'Battery Rules' },
  { parent_code: 'CABLE_WIRE', parent_name: 'Cables & Wires', sub_code: 'copper_wire', sub_name: 'Insulated Copper Cable & Wire', is_hazardous: false },
  { parent_code: 'CRT', parent_name: 'Cathode Ray Tubes', sub_code: 'tv_crt', sub_name: 'CRT Television Tube (Leaded)', is_hazardous: true, epr_schedule1_hint: 'CEEW1' },
  { parent_code: 'LCD_LED_PANEL', parent_name: 'Flat Panels', sub_code: 'laptop_panel', sub_name: 'Laptop Screen Display Panel', is_hazardous: true, epr_schedule1_hint: 'ITEW3' },
  { parent_code: 'MOTOR_MAGNET', parent_name: 'Motors & Magnets', sub_code: 'compressor_motor', sub_name: 'Fridge / AC Compressor Motor', is_hazardous: false, epr_schedule1_hint: 'CEEW2' },
  { parent_code: 'METAL_SCRAP', parent_name: 'Metal Scrap', sub_code: 'copper_scrap', sub_name: 'Pure Heavy Copper Scrap', is_hazardous: false },
  { parent_code: 'WHOLE_DEVICE', parent_name: 'Whole Devices', sub_code: 'laptop', sub_name: 'Complete Laptop Device', is_hazardous: false, epr_schedule1_hint: 'ITEW3' },
  { parent_code: 'LIGHTING', parent_name: 'Lighting Equipment', sub_code: 'cfl_bulb', sub_name: 'CFL Bulb (Contains Mercury)', is_hazardous: true, epr_schedule1_hint: 'CEEW5' },
];

export const MOCK_RATE_CARDS: RecyclerRateCard[] = [
  { id: 'rc-1', recycler_id: CURRENT_RECYCLER.id, parent_code: 'PCB', sub_code: 'mobile_pcb', rate_per_kg: 450.00, effective_date: '2026-09-01' },
  { id: 'rc-2', recycler_id: CURRENT_RECYCLER.id, parent_code: 'PCB', sub_code: 'computer_motherboard', rate_per_kg: 330.00, effective_date: '2026-09-01' },
  { id: 'rc-3', recycler_id: CURRENT_RECYCLER.id, parent_code: 'BATTERY', sub_code: 'li_ion_mobile_laptop', rate_per_kg: 180.00, effective_date: '2026-09-02' },
  { id: 'rc-4', recycler_id: CURRENT_RECYCLER.id, parent_code: 'BATTERY', sub_code: 'lead_acid_ups_inverter_auto', rate_per_kg: 95.00, effective_date: '2026-08-28' },
  { id: 'rc-5', recycler_id: CURRENT_RECYCLER.id, parent_code: 'CABLE_WIRE', sub_code: 'copper_wire', rate_per_kg: 385.00, effective_date: '2026-09-03' },
  { id: 'rc-6', recycler_id: CURRENT_RECYCLER.id, parent_code: 'LCD_LED_PANEL', sub_code: 'laptop_panel', rate_per_kg: 110.00, effective_date: '2026-08-30' },
  { id: 'rc-7', recycler_id: CURRENT_RECYCLER.id, parent_code: 'MOTOR_MAGNET', sub_code: 'compressor_motor', rate_per_kg: 140.00, effective_date: '2026-09-01' },
  { id: 'rc-8', recycler_id: CURRENT_RECYCLER.id, parent_code: 'METAL_SCRAP', sub_code: 'copper_scrap', rate_per_kg: 535.00, effective_date: '2026-09-03' },
  { id: 'rc-9', recycler_id: CURRENT_RECYCLER.id, parent_code: 'WHOLE_DEVICE', sub_code: 'laptop', rate_per_kg: 490.00, effective_date: '2026-09-02' },
];

export const MOCK_MATCHED_LOTS: LotMatch[] = [
  {
    id: 'match-1',
    lot_id: 'lot-101',
    recycler_id: CURRENT_RECYCLER.id,
    score: 94.5,
    rank: 1,
    status: 'offered',
    offered_at: '15 mins ago',
    lot: {
      id: 'lot-101',
      collector_id: 'c0000000-0000-0000-0000-000000000001',
      collector_name: 'Ramesh Kabadiwala',
      parent_code: 'PCB',
      sub_code: 'mobile_pcb',
      condition: 'scrap',
      weight_kg: 14.20,
      hazard_flags: ['acid_leaching_risk'],
      ai_suggested_rate_per_kg: 450.00,
      ai_confidence: 0.96,
      estimated_value: 6390.00,
      ward_name: 'Shahdara / Mandoli Ward',
      status: 'matched',
      client_created_at: 'Today, 11:20 AM',
    },
  },
  {
    id: 'match-2',
    lot_id: 'lot-102',
    recycler_id: CURRENT_RECYCLER.id,
    score: 89.0,
    rank: 1,
    status: 'offered',
    offered_at: '45 mins ago',
    lot: {
      id: 'lot-102',
      collector_id: 'c0000000-0000-0000-0000-000000000002',
      collector_name: 'Okhla Collection Hub',
      parent_code: 'BATTERY',
      sub_code: 'li_ion_mobile_laptop',
      condition: 'scrap',
      weight_kg: 28.50,
      hazard_flags: ['fire_hazard', 'lithium_swelling'],
      ai_suggested_rate_per_kg: 180.00,
      ai_confidence: 0.92,
      estimated_value: 5130.00,
      ward_name: 'Okhla Phase-1 Ward',
      status: 'matched',
      client_created_at: 'Today, 10:45 AM',
    },
  },
  {
    id: 'match-3',
    lot_id: 'lot-103',
    recycler_id: CURRENT_RECYCLER.id,
    score: 82.5,
    rank: 2,
    status: 'offered',
    offered_at: '2 hours ago',
    lot: {
      id: 'lot-103',
      collector_id: 'c0000000-0000-0000-0000-000000000001',
      collector_name: 'Ramesh Kabadiwala',
      parent_code: 'CABLE_WIRE',
      sub_code: 'copper_wire',
      condition: 'scrap',
      weight_kg: 45.00,
      hazard_flags: ['open_copper'],
      ai_suggested_rate_per_kg: 385.00,
      ai_confidence: 0.98,
      estimated_value: 17325.00,
      ward_name: 'Mandoli Industrial',
      status: 'matched',
      client_created_at: 'Today, 09:15 AM',
    },
  },
  {
    id: 'match-4',
    lot_id: 'lot-104',
    recycler_id: CURRENT_RECYCLER.id,
    score: 78.0,
    rank: 2,
    status: 'offered',
    offered_at: '4 hours ago',
    lot: {
      id: 'lot-104',
      collector_id: 'c0000000-0000-0000-0000-000000000003',
      collector_name: 'Seelampur Informal Aggregator',
      parent_code: 'WHOLE_DEVICE',
      sub_code: 'laptop',
      condition: 'damaged',
      weight_kg: 18.00,
      hazard_flags: ['battery_present'],
      ai_suggested_rate_per_kg: 490.00,
      ai_confidence: 0.89,
      estimated_value: 8820.00,
      ward_name: 'North East Delhi',
      status: 'matched',
      client_created_at: 'Yesterday, 04:30 PM',
    },
  },
];

export const MOCK_PRICE_BOARD: PriceBoardItem[] = [
  {
    parent_code: 'PCB',
    parent_name: 'Printed Circuit Boards',
    sub_code: 'mobile_pcb',
    sub_name: 'Mobile Phone Motherboard',
    is_hazardous: true,
    avg_price_per_kg: 452.50,
    min_price_per_kg: 430.00,
    max_price_per_kg: 465.00,
    data_points_count: 18,
    trend_percentage: 3.4,
    latest_price_date: 'Today',
  },
  {
    parent_code: 'PCB',
    parent_name: 'Printed Circuit Boards',
    sub_code: 'computer_motherboard',
    sub_name: 'Computer Motherboard',
    is_hazardous: true,
    avg_price_per_kg: 322.00,
    min_price_per_kg: 310.00,
    max_price_per_kg: 335.00,
    data_points_count: 14,
    trend_percentage: 1.8,
    latest_price_date: 'Today',
  },
  {
    parent_code: 'BATTERY',
    parent_name: 'Batteries',
    sub_code: 'li_ion_mobile_laptop',
    sub_name: 'Lithium-Ion / Li-Polymer',
    is_hazardous: true,
    avg_price_per_kg: 182.00,
    min_price_per_kg: 170.00,
    max_price_per_kg: 190.00,
    data_points_count: 22,
    trend_percentage: 4.2,
    latest_price_date: 'Today',
  },
  {
    parent_code: 'BATTERY',
    parent_name: 'Batteries',
    sub_code: 'lead_acid_ups_inverter_auto',
    sub_name: 'Lead-Acid Inverter / UPS',
    is_hazardous: true,
    avg_price_per_kg: 94.50,
    min_price_per_kg: 92.00,
    max_price_per_kg: 98.00,
    data_points_count: 29,
    trend_percentage: 0.8,
    latest_price_date: 'Today',
  },
  {
    parent_code: 'CABLE_WIRE',
    parent_name: 'Cables & Wires',
    sub_code: 'copper_wire',
    sub_name: 'Insulated Copper Wire',
    is_hazardous: false,
    avg_price_per_kg: 386.00,
    min_price_per_kg: 370.00,
    max_price_per_kg: 395.00,
    data_points_count: 35,
    trend_percentage: 2.1,
    latest_price_date: 'Today',
  },
  {
    parent_code: 'METAL_SCRAP',
    parent_name: 'Metal Scrap',
    sub_code: 'copper_scrap',
    sub_name: 'Pure Heavy Copper Scrap',
    is_hazardous: false,
    avg_price_per_kg: 532.00,
    min_price_per_kg: 520.00,
    max_price_per_kg: 545.00,
    data_points_count: 12,
    trend_percentage: 1.5,
    latest_price_date: 'Yesterday',
  },
  {
    parent_code: 'MOTOR_MAGNET',
    parent_name: 'Motors & Magnets',
    sub_code: 'compressor_motor',
    sub_name: 'Fridge / AC Compressor Motor',
    is_hazardous: false,
    avg_price_per_kg: 139.00,
    min_price_per_kg: 135.00,
    max_price_per_kg: 145.00,
    data_points_count: 16,
    trend_percentage: -0.5,
    latest_price_date: 'Today',
  },
];

export const MOCK_PICKUP_REQUESTS: CustomerPickupRequest[] = [
  {
    id: 'req-01',
    customer_phone: '+91 98112 34567',
    pickup_address: 'Flat 402, Mayur Vihar Phase-1, East Delhi',
    material_description: '2 Old laptops, 1 tablet, mixed cables and 4 mobile phones',
    parent_code: 'WHOLE_DEVICE',
    sub_code: 'laptop',
    approx_weight_kg: 6.5,
    preferred_date: 'Tomorrow (10:00 AM - 01:00 PM)',
    is_bulk: false,
    status: 'assigned',
    assigned_collector_name: 'Ramesh Kabadi (Assigned)',
    created_at: '2 hours ago',
  },
  {
    id: 'req-02',
    customer_phone: '+91 99990 12345',
    pickup_address: 'TechPark Tower B, Okhla Industrial Area Ph-2',
    material_description: 'Decommissioned server power supplies, heavy wiring harnesses, 12 server motherboards',
    parent_code: 'PCB',
    sub_code: 'computer_motherboard',
    approx_weight_kg: 85.0,
    preferred_date: '05 Sep 2026 (02:00 PM - 05:00 PM)',
    is_bulk: true,
    status: 'pending',
    created_at: 'Today, 08:30 AM',
  },
  {
    id: 'req-03',
    customer_phone: '+91 98710 99881',
    pickup_address: 'Pocket B, Dilshad Garden, Shahdara',
    material_description: 'CRT TV set, defective UPS battery',
    parent_code: 'CRT',
    sub_code: 'tv_crt',
    approx_weight_kg: 22.0,
    preferred_date: '06 Sep 2026 (11:00 AM - 02:00 PM)',
    is_bulk: false,
    status: 'scheduled',
    assigned_collector_name: 'Suresh Scrap Dealer',
    created_at: 'Yesterday',
  },
];

export const MOCK_SAFETY_GUIDES: SafetyItem[] = [
  {
    id: 'safe-1',
    parent_code: 'BATTERY',
    language: 'hi',
    media_type: 'infographic',
    title: 'बैटरी को कभी न जलाएं या हथौड़े से न तोड़ें',
    description: 'लिथियम और लेड-एसिड बैटरियों से जहरीली गैस और अचानक आग लगने का गंभीर खतरा होता है। इसे बिना खोले सीधे अधिकृत रिसाइक्लर को दें।',
  },
  {
    id: 'safe-2',
    parent_code: 'CRT',
    language: 'hi',
    media_type: 'infographic',
    title: 'सीआरटी कांच में जहरीला सीसा (Lead) होता है',
    description: 'सीआरटी ट्यूब फोड़ने से जहरीली कांच की धूल सांस में जाती है। स्क्रीन को टूटने से बचाएं और दस्ताने पहनकर उठाएं।',
  },
  {
    id: 'safe-3',
    parent_code: 'CABLE_WIRE',
    language: 'hi',
    media_type: 'infographic',
    title: 'तारों को खुले में कभी न जलाएं (No Wire Burning)',
    description: 'प्लास्टिक जलने से डायोक्सिन जैसी कैंसरकारी गैस निकलती है। तांबा निकालने के लिए वायर-स्ट्रिपर का उपयोग करें।',
  },
  {
    id: 'safe-4',
    parent_code: 'LIGHTING',
    language: 'hi',
    media_type: 'infographic',
    title: 'सीएफएल बल्ब और ट्यूबलाइट में पारा (Mercury) होता है',
    description: 'पारे की भाप नसों को स्थायी नुकसान पहुंचाती है। कांच टूटने पर मुंह ढकें और सीधे अधिकृत प्लांट को भेजें।',
  },
];
